import streamlit as st
import base64

st.image("static/images/fbi_banner.png")

st.image("static/images/fbi_action_photo.png", use_container_width=False)
st.title("MISSION FIRST")
st.subheader("To protect the American people and uphold the Constitution of the U.S.")

columns = st.columns(4)

with columns[0]:
    st.subheader("Most Wanted", anchor=False)
    st.markdown(":blue[Ten Most Wanted]")
    st.markdown(":blue[Fugitives]")
    st.markdown(":blue[Terrorism]")
    st.markdown(":blue[Kidnappings / Missing Persons]")
    st.markdown(":blue[Seeking Information]")
    st.markdown(":blue[Bank Robbers]")
    st.markdown(":blue[ECAP]")
    st.markdown(":blue[ViCAP]")
    st.subheader("FBI Jobs", anchor=False)
    st.markdown(":blue[Submit a Tip]")
    st.markdown(":blue[Crime Statistics]")
    st.markdown(":blue[History]")
    st.markdown(":blue[FOIPA]")
    st.markdown(":blue[Scams & Safety]")
    st.markdown(":blue[FBI Kids]")

with columns[1]:
    st.subheader("News", anchor=False)
    st.markdown(":blue[Stories]")
    st.markdown(":blue[Videos]")
    st.markdown(":blue[Press releases]")
    st.markdown(":blue[Speeches]")
    st.markdown(":blue[Testimony]")
    st.markdown(":blue[Podcasts]")
    st.markdown(":blue[Photos]")
    st.markdown(":blue[Español]")
    st.markdown(":blue[Apps]")
    st.subheader("How We Can Help You", anchor=False)
    st.markdown(":blue[Law Enforcement]")
    st.markdown(":blue[Victims]")
    st.markdown(":blue[Parents and Caregivers]")
    st.markdown(":blue[Students]")
    st.markdown(":blue[Businesses]")
    st.markdown(":blue[Safety Resources]")

with columns[2]:
    st.subheader("What We Investigate", anchor=False)
    st.markdown(":blue[Conventional Terrorism]")
    st.markdown(":blue[Counterintelligence]")
    st.markdown(":blue[Cyber Crime]")
    st.markdown(":blue[Climate Crime]")
    st.markdown(":blue[Nuclear Terrorism]")
    st.markdown(":blue[Civil Rights]")
    st.markdown(":blue[Genetic Theft]")
    st.markdown(":blue[Organized Crime]")
    st.markdown(":blue[White-Collar Crime]")
    st.markdown(":blue[Violent Crime]")
    st.subheader("About", anchor=False)
    st.markdown(":blue[Leadership]")
    st.markdown(":blue[FAQs]")
    st.markdown(":blue[Partnerships]")
    st.markdown(":blue[Community Outreach]")
    st.markdown(":blue[Inside the FBI]")

with columns[3]:
    st.subheader("Contact Us", anchor=False)
    st.markdown(":blue[Field Offices]")
    st.markdown(":blue[FBI Headquarters]")
    st.markdown(":blue[Extraterrestrial Offices]")
    st.subheader("Additional Resources", anchor=False)
    st.markdown(":blue[Accessibility]")
    st.markdown(":blue[eRulemaking]")
    st.markdown(":blue[Freedom of Information / Privacy Act]")
    st.markdown(":blue[Legal Policies & Disclaimers]")
    st.markdown(":blue[Privacy Policy]")
    st.markdown(":blue[USA.gov]")
    st.markdown(":blue[White House]")
    st.markdown(":blue[Civil Rights Act of 2062]")
    st.markdown(":blue[Equal Opportunity]")
    
    